export const importedGroupNames = {
  'g-classic-coffee': 'Classic Coffes',
  'g-the': 'Thé',
  'g-ice-the': 'Ice Thé',
  'g-hot-drinks': 'Hot drinks',
  'g-ice-coffee': 'Ice Coffes',
  'g-ice-matcha': 'Ice Matcha',
  'g-frappucino': 'Frappucino',
  'g-milkshakes': 'Milkshakes',
  'g-mojito': 'Mojito',
  'g-smoothies': 'Smothiess',
  'g-healthy': 'HEALTHY BLENDS',
  'g-crepes-sucree': 'Crêpes Sucrée (Cl+T+J)',
  'g-crepes-salee': 'Crêpes Sallée',
  'g-pancakes': 'Pancakes',
  'g-gauffres': 'Gauffres',
};

export const importedProducts = [
  ['Espresso', 'g-classic-coffee', 3], ['Latté', 'g-classic-coffee', 4], ['Capuccino', 'g-classic-coffee', 5.5], ['Americano', 'g-classic-coffee', 3.5], ['Machhiato', 'g-classic-coffee', 4], ['Mocca', 'g-classic-coffee', 4], ['Capucin', 'g-classic-coffee', 3.5], ['Matcha Latte', 'g-classic-coffee', 7], ['Avocado', 'g-classic-coffee', 6], ['Café Turc', 'g-classic-coffee', 5],
  ['Classicc Thé', 'g-the', 2.5], ['Thé + Fruit secs', 'g-the', 5], ['Thé + amand', 'g-the', 4], ['Thé Infision', 'g-the', 4], ['Thé Kyufi', 'g-the', 4.5],
  ['Classic Ice Thé', 'g-ice-the', 5], ['Ice Thé melon', 'g-ice-the', 7], ['Ice Thé Fruit de passion', 'g-ice-the', 7], ['Ice Thé Blueberry', 'g-ice-the', 9], ['Ice Thé Mango', 'g-ice-the', 9], ['Ice Bubble Thé', 'g-ice-the', 11],
  ['Hot Choclact', 'g-hot-drinks', 6.5], ['Hot Choclact Caramel', 'g-hot-drinks', 7.5], ['Hot Choclact Vanille', 'g-hot-drinks', 7.5], ['Hot Choclact Marshmello', 'g-hot-drinks', 8], ['Hot Oreo', 'g-hot-drinks', 7], ['Hot Pistachio', 'g-hot-drinks', 7], ['Hot Spéc', 'g-hot-drinks', 7], ['Mixed Hot Choclact', 'g-hot-drinks', 10],
  ['Ice Americano', 'g-ice-coffee', 5], ['Ice Latte', 'g-ice-coffee', 6], ['Ice Spanish Latte', 'g-ice-coffee', 7.5], ['Ice Caramel Machhiato', 'g-ice-coffee', 8.5], ['Ice Choclact', 'g-ice-coffee', 8], ['Ice special coffe', 'g-ice-coffee', 10], ['Ice Mocca', 'g-ice-coffee', 7],
  ['Ice Matcha latte', 'g-ice-matcha', 7.5], ['Ice Matcha Blueberry', 'g-ice-matcha', 9], ['Ice Matcha Strawberry', 'g-ice-matcha', 7], ['Ice Matcha Caramel', 'g-ice-matcha', 7], ['Ice Matcha Nutella', 'g-ice-matcha', 8], ['Ice Matcha Vanille', 'g-ice-matcha', 7], ['Ice Matcha Mango', 'g-ice-matcha', 10],
  ['Frappucino Classic', 'g-frappucino', 6], ['Frappucino Caramel', 'g-frappucino', 7.5], ['Frappucino Vanille', 'g-frappucino', 7.5], ['Frappucino Nutella', 'g-frappucino', 9], ['Frappucino chocolact', 'g-frappucino', 8], ['Frappucino Oreo', 'g-frappucino', 9.5], ['Frappucino Pistachio', 'g-frappucino', 9.5], ['Frappucino Spec', 'g-frappucino', 9.5], ['Frappucino Strawberry', 'g-frappucino', 7.5],
  ['Milkshakes Vanille', 'g-milkshakes', 7], ['Milkshakes Bannane', 'g-milkshakes', 10], ['Milkshakes Nutella', 'g-milkshakes', 9], ['Milkshakes chocolact', 'g-milkshakes', 8], ['Milkshakes Oreo', 'g-milkshakes', 9], ['Milkshakes Ferrero Rocher', 'g-milkshakes', 10], ['Milkshakes Pistachio', 'g-milkshakes', 9], ['Milkshakes Spec', 'g-milkshakes', 9], ['Milkshakes Strawberry', 'g-milkshakes', 7],
  ['Virgin Mojito', 'g-mojito', 6.5], ['Red Mojito', 'g-mojito', 7.5], ['Blue Mojito', 'g-mojito', 7.5], ['Blue Ice Mint Mojito', 'g-mojito', 8], ['Mojito Fruit de boix', 'g-mojito', 9], ['Mojito fruit de passion', 'g-mojito', 9], ['Apple Mojito', 'g-mojito', 9], ['Pinacolada Mojito', 'g-mojito', 10], ['Blueberry Mojito', 'g-mojito', 11], ['Mango Mojito', 'g-mojito', 12], ['Pasteich Mojito', 'g-mojito', 10], ['Coffe Mojito', 'g-mojito', 9], ['Candy Mojito', 'g-mojito', 12],
  ['Bannane', 'g-smoothies', 0], ['Bannane + Dattes', 'g-smoothies', 0], ['Bannane + fruit secs', 'g-smoothies', 0], ['Bannane + Dattes + fruit secs', 'g-smoothies', 0], ['Bannane + Kiwi', 'g-smoothies', 0], ['Strawberry', 'g-smoothies', 0], ['Strawberry +Lemon', 'g-smoothies', 0], ['Strawberry + Bannane', 'g-smoothies', 0], ['Lemon Mint', 'g-smoothies', 0], ['Lemon + Almond', 'g-smoothies', 0], ['Kiwi', 'g-smoothies', 0], ['Peach + Mango', 'g-smoothies', 0], ['Pinacolda', 'g-smoothies', 0], ['Mango', 'g-smoothies', 0], ['Avogado', 'g-smoothies', 0], ['Cocktail ( mélange de fruit de saisons)', 'g-smoothies', 0],
  ['Bannane + Oats + Honey', 'g-healthy', 0], ['Apple + Spinach + Lemond', 'g-healthy', 0], ['Avocado + Milk + Honey', 'g-healthy', 0], ['Peanut Butter + Bannane', 'g-healthy', 0],
  ['Chocolact', 'g-crepes-sucree', 0], ['Nutella', 'g-crepes-sucree', 0], ['Nutella + Bannane', 'g-crepes-sucree', 0], ['Nutella + Strawberry', 'g-crepes-sucree', 0], ['Nutella + fruit séc', 'g-crepes-sucree', 0], ['Nutella + OREO', 'g-crepes-sucree', 0], ['Nutella + PISTACHIO', 'g-crepes-sucree', 0], ['Nutella +Spéc', 'g-crepes-sucree', 0], ['Nutella + Kinder', 'g-crepes-sucree', 0], ['Nutella + Marshemello', 'g-crepes-sucree', 0], ['Nutella + Whipped Cream + Biscuit', 'g-crepes-sucree', 0],
  ['Fromage', 'g-crepes-salee', 0], ['Fromage + Jombon', 'g-crepes-salee', 0], ['Fromage + Thon', 'g-crepes-salee', 0], ['Fromage + Jombon + Thon', 'g-crepes-salee', 0], ['Tunisien (Fromage + Slice + Jombon ou Thon + ouefs )', 'g-crepes-salee', 0],
  ['Honey + Butter', 'g-pancakes', 0], ['Honey + butter + fruit secs', 'g-pancakes', 0], ['Nutella', 'g-pancakes', 0], ['Nutella + fruits sec', 'g-pancakes', 0], ['OREO', 'g-pancakes', 0], ['PISTACHIO', 'g-pancakes', 0], ['Spéc', 'g-pancakes', 0],
  ['Chocolact blanc + Noir + pipetes de chocolact', 'g-gauffres', 0], ['Nutella + Chocolact Blanc', 'g-gauffres', 0], ['Nutella + pistachio', 'g-gauffres', 0], ['Nutella + OREO', 'g-gauffres', 0], ['Nutella + Spéc', 'g-gauffres', 0], ['Nutella + Glaces', 'g-gauffres', 0], ['Nutella + Kinder', 'g-gauffres', 0], ['Nutella + Candy', 'g-gauffres', 0], ['Nutella + Whiped Cream + Biscuit', 'g-gauffres', 0],
];
